### ISSUE TITLE
Bad styling over https

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#83]
It seems that the http (not https) scheme is used in some places, likely due to APPROOT. The solution is most likely to use URLs without a scheme, e.g. `//www.stackage.org/foo/bar` or even without a domain name, e.g. `/foo/bar`. However, we need to make sure that when making such a change, necessary absolute links still work.

Pinging @chrisdone

**Comment by DanBurton** [comment]
Are there any absolute links to the stackage.org domain that must remain absolute? Or are you just referring to absolute links that lead outside of stackage.org?

**Comment by snoyberg** [comment]
One example is available at: http://www.stackage.org/snapshot/lts-1.13/cabal.config. There *might* be others, I'm not certain yet.

**Comment by DanBurton** [comment]
How irritating it is that cabal doesn't support https, otherwise I'd just suggest using `ApprootRequest` and `isSecure`.

**Comment by DanBurton** [comment]
Related, but not really an issue for this repository: https://stackage.org should redirect to https://www.stackage.org.

**Comment by snoyberg** [comment]
Perhaps the solution here should be to set the approot to
https://www.stackage.org, and in the specific cases where we need to
support cabal-install, we do a s@^https://@http://@, what do you think?
(And no, I don't mean literally using a regex.)

**Comment by DanBurton** [comment]
The files that are causing issues are the static/combined/blah.css and static/combined/blah.js files. We could leave the approot as http:// if there were some way to convince Yesod to link these resources schemelessly (// instead of http://).

If that's not possible, then yes, we can just default to https and special case the cabal links.

**Comment by DanBurton** [comment]
Actually the former solution I suggested is bad, because clicking any links generated by yesod will drop a user out of their https browsing session and into an http session, which sort of defeats the purpose of encrypted connections.

Perhaps a better solution would be to make the approot schemeless, and then special case the cabal links to prepend `http:`.

**Comment by chrisdone** [comment]
Perhaps [urlRenderOverride](https://github.com/fpco/stackage-server/blob/master/Foundation.hs#L135..L136) can be relevant for that?

**Comment by DanBurton** [comment]
I've made the cabal.config generation code slightly more robust, so no matter what we make approot or urlRenderOverride do, it should correctly convert it to http.

I recommend making the approot `//www.stackage.org` with no scheme, or alternatively, using ApprootRequest to generate a scheme that always matches the request.

**Comment by snoyberg** [comment]
Good move on the code there. @ketzacoatl can we update the APPROOT variable used during deployment to be `//www.stackage.org`, *after* this code change goes through?

**Comment by ketzacoatl** [comment]
@snoyberg Yes - when we deploy the `.keter`, there is a key that configures app_root in the formula. We can easily update them at the same time.

**Comment by snoyberg** [comment]
After more thought, let's make the approot `https://www.stackage.org`. Motivation: we would ideally like all requests to be secure. Unfortunately, cabal is broken and doesn't support SSL, so we can't *force* people to use it. But it's a good idea if all generated links are secure.

**Comment by snoyberg** [comment]
This is now resolved, thanks guys!
