### ISSUE TITLE
Define custom search engines for Hoogle (and packages?)

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#94]
I've added two custom search engines for my personal use in Chrome, which have both turned out to be very convenient:

* Stackage Hoogle: http://www.stackage.org/lts/hoogle?q=%s
* Stackage package page: https://www.stackage.org/package/%s

I've assigned keywords of `hoo` and `p` respectively, though the keywords could be whatever people want. I believe there's a way to add links to the Stackage homepage to add these search engines for end users, but I'm unfamiliar with the API. It would be a useful addition to consider.

**Comment by snoyberg** [comment]
Possibly related: https://developers.google.com/custom-search/docs/context

**Comment by drwebb** [comment]
So I've done a little digging and possibly related is [the openseach spec] (http://www.opensearch.org/Home). All the major browsers seem to support this standard. 

Related SO Q&A: http://stackoverflow.com/questions/1317051/making-usage-of-google-chromes-omnibox-tab-feature-for-on-personal-website

**Comment by snoyberg** [comment]
That could be what we're looking for here, yes.

**Comment by drwebb** [comment]
I've pushed xml files to an osd branch https://github.com/fpco/stackage-server/tree/osd

I tested in both Firefox and Chrome. Firefox displays the ability to add both engines. Chrome only lists the hoogle engine, I assume because it is the first one specified. Also, adding the engine on Chrome is much more tedious (you have to go into Settings).

Firefox seems to support the cool autocomplete in your search box feature, if we have a place to hook that in. I know the official hoogle has picked up that feature recently.

**Comment by snoyberg** [comment]
That looks good, can you send it as a pull request?

**Comment by snoyberg** [comment]
@drwebb Pinging again, can you send a pull request for this change?

**Comment by drwebb** [comment]
Committed changes
